FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN CGO_ENABLED=1 go build -ldflags="-s -w" -o scheduler ./cmd/scheduler

FROM alpine:3.19
RUN apk --no-cache add ca-certificates sqlite-libs
WORKDIR /app
COPY --from=builder /app/scheduler .
COPY config-scheduler.yaml ./config-scheduler.yaml
EXPOSE 8081
CMD ["./scheduler"]
